apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2
    spec:
      containers:
      - name: frontend2
        image: frontend2:latest
        imagePullPolicy: Never # Prevent pulling from a registry
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend2-service
spec:
  type: NodePort
  selector:
    app: frontend2
  ports:
  - port: 80
    nodePort: 30002