apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name: frontend1
        image: frontend1:latest
        imagePullPolicy: Never # Prevent pulling from a registry
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend1-service
spec:
  type: NodePort
  selector:
    app: frontend1
  ports:
  - port: 80
    nodePort: 30001