apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # Base64 encoded value of "rootpassword"
  MYSQL_USER: YXBwdXNlcg==              # Base64 encoded value of "appuser"
  MYSQL_PASSWORD: YXBwcGFzc3dvcmQ=      # Base64 encoded value of "apppassword"
  MYSQL_DATABASE: bWljcm9zZXJ2aWNlc2Ri  # Base64 encoded value of "microservicesdb"
